steps:
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements-test.txt", "--user"]

  - name: python
    entrypoint: python
    args: ["-m", "pytest", "--junitxml=${SHORT_SHA}_test_log.xml"]
  # [END cloudbuild_python_tests_yaml]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}.pkg.dev/${GOOGLE_CLOUD_PROJECT}/${GOOGLE_CLOUD_PROJECT}/${_IMAGE_NAME}:${SHORT_SHA}",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}.pkg.dev/${GOOGLE_CLOUD_PROJECT}/${GOOGLE_CLOUD_PROJECT}/${_IMAGE_NAME}:${SHORT_SHA}",
      ]

  - name: google/cloud-sdk
    args: [
        "gcloud",
        "run",
        "deploy",
        "cloudrun-fastapi",
        # "helloworld-${SHORT_SHA}",
        "--image=${_REGION}.pkg.dev/${GOOGLE_CLOUD_PROJECT}/${GOOGLE_CLOUD_PROJECT}/${_IMAGE_NAME}:${SHORT_SHA}",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

substitutions:
  _IMAGE_NAME: cloudrun-fastapi
  _REGION: us-central1-docker
